import { useState } from 'react'
import { ExternalLink, KeyRound, LockKeyhole, Plus, Server, ShieldAlert, Trash2 } from 'lucide-react'
import type { Credential, Device } from '@autosecure/shared'
import { Card } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { cn } from '@/lib/utils'
import { patch, post, remove } from './api.ts'
import { Badge, Button, ConfirmButton, Empty, Field, FormActions, Input, Modal, Notice, PageHeader, Select, submitForm } from './components.tsx'

type Props = { devices: Device[]; credentials: Credential[]; reload: () => Promise<void>; notify: (message: string, tone?: 'success' | 'error') => void }

export function DevicesPage({ devices, credentials, reload, notify }: Props) {
  const [deviceModal, setDeviceModal] = useState<Device | 'new' | null>(null)
  const [credentialModal, setCredentialModal] = useState(false)
  const [editCredential, setEditCredential] = useState<Credential | null>(null)

  const saveDevice = async (data: FormData) => {
    const body = { name: String(data.get('name') || ''), baseUrl: String(data.get('baseUrl') || ''), credentialId: String(data.get('credentialId') || '') || null, ignoreHttpsErrors: data.get('ignoreHttpsErrors') === 'on' }
    try { if (deviceModal !== 'new' && deviceModal) await patch(`/api/devices/${deviceModal.id}`, body); else await post('/api/devices', body); setDeviceModal(null); await reload(); notify('Gerät wurde gespeichert.') }
    catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') }
  }
  const saveCredential = async (data: FormData) => {
    const body = { name: String(data.get('name') || ''), username: String(data.get('username') || ''), password: String(data.get('password') || '') }
    try { if (editCredential) await patch(`/api/credentials/${editCredential.id}`, { ...body, password: body.password || undefined }); else await post('/api/credentials', body); setEditCredential(null); await reload(); notify('Zugangsdatenprofil wurde gespeichert.') }
    catch (error) { notify(error instanceof Error ? error.message : String(error), 'error') }
  }

  return <>
    <PageHeader eyebrow="Inventar" title="Geräte" description="Firewalls und andere Zielsysteme für deine sichtbaren Automationen." actions={<><Button variant="secondary" icon={<KeyRound/>} onClick={() => setCredentialModal(true)}>Zugangsdaten</Button><Button icon={<Plus/>} onClick={() => setDeviceModal('new')}>Gerät hinzufügen</Button></>}/>
    <div className="mb-4 flex flex-wrap gap-x-8 gap-y-2 rounded-lg border bg-white px-4 py-3 text-sm"><span><strong>{devices.length}</strong> <span className="text-muted-foreground">Geräte</span></span><span><strong>{credentials.length}</strong> <span className="text-muted-foreground">Zugangsdatenprofile</span></span><span className="flex items-center gap-1.5"><ShieldAlert className="size-3.5 text-amber-600"/><strong>{devices.filter((device) => device.ignoreHttpsErrors).length}</strong> <span className="text-muted-foreground">Zertifikatsausnahmen</span></span></div>
    <Card className="overflow-hidden shadow-none">{devices.length ? <Table><TableHeader><TableRow><TableHead>Gerät</TableHead><TableHead>Start-URL</TableHead><TableHead>Zugangsdaten</TableHead><TableHead>Tabellenwerte</TableHead><TableHead className="w-28"/></TableRow></TableHeader><TableBody>{devices.map((device) => <TableRow key={device.id}><TableCell><button className="font-medium hover:underline" onClick={() => setDeviceModal(device)}>{device.name}</button>{device.ignoreHttpsErrors && <Badge tone="warning" className="ml-2">HTTPS-Ausnahme</Badge>}</TableCell><TableCell><a href={device.baseUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-mono text-xs text-blue-700 hover:underline">{device.baseUrl}<ExternalLink className="size-3"/></a></TableCell><TableCell>{device.credentialName || <span className="text-muted-foreground">Nicht zugewiesen</span>}</TableCell><TableCell>{Object.values(device.data).filter(Boolean).length}</TableCell><TableCell className="text-right"><Button variant="ghost" onClick={() => setDeviceModal(device)}>Bearbeiten</Button></TableCell></TableRow>)}</TableBody></Table> : <Empty icon={<Server/>} title="Noch keine Geräte" text="Lege deine erste Firewall an oder nutze die lokale Demo-Firewall." action={<Button icon={<Plus/>} onClick={() => setDeviceModal('new')}>Erstes Gerät anlegen</Button>}/>}</Card>

    {deviceModal && <Modal title={deviceModal === 'new' ? 'Gerät hinzufügen' : 'Gerät bearbeiten'} description="Diese URL wird bei Aufnahme und Ausführung als Startpunkt verwendet." onClose={() => setDeviceModal(null)}><form onSubmit={submitForm(saveDevice)}><div className="grid gap-5 px-6 py-5"><Field label="Name"><Input name="name" defaultValue={deviceModal === 'new' ? '' : deviceModal.name} placeholder="z. B. Firewall Berlin" required autoFocus/></Field><Field label="Start-URL"><Input name="baseUrl" type="url" defaultValue={deviceModal === 'new' ? '' : deviceModal.baseUrl} placeholder="https://192.168.1.1" required/></Field><Field label="Zugangsdatenprofil"><Select name="credentialId" defaultValue={deviceModal === 'new' ? '' : deviceModal.credentialId || ''}><option value="">Keine Zuordnung</option>{credentials.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</Select></Field><label className="flex cursor-pointer items-start gap-3 rounded-lg border p-3"><input name="ignoreHttpsErrors" type="checkbox" className="mt-0.5 size-4 accent-zinc-900" defaultChecked={deviceModal !== 'new' && deviceModal.ignoreHttpsErrors}/><span><strong className="block text-sm font-medium">Selbstsigniertes Zertifikat zulassen</strong><small className="text-xs text-muted-foreground">Nur für vertrauenswürdige interne Geräte aktivieren.</small></span></label></div><div className="flex border-t bg-muted/20 px-6 py-4">{deviceModal !== 'new' && <ConfirmButton onConfirm={async () => { await remove(`/api/devices/${deviceModal.id}`); setDeviceModal(null); await reload(); notify('Gerät wurde gelöscht.') }}>Gerät löschen</ConfirmButton>}<FormActions onCancel={() => setDeviceModal(null)}/></div></form></Modal>}

    {credentialModal && <Modal title="Zugangsdaten" description="Wiederverwendbare Profile für Geräte und Webseiten." onClose={() => { setCredentialModal(false); setEditCredential(null) }} wide><div className="grid md:grid-cols-[1.1fr_.9fr]"><div className="border-b p-5 md:border-r md:border-b-0"><Notice tone="warning" title="Lokale Klartextspeicherung">Passwörter werden wie festgelegt unverschlüsselt in der lokalen SQLite-Datei gespeichert.</Notice><div className="mt-4 space-y-2">{credentials.map((item) => <button key={item.id} className={cn('flex w-full items-center gap-3 rounded-lg border p-3 text-left hover:bg-muted', editCredential?.id === item.id && 'border-zinc-400 bg-muted')} onClick={() => setEditCredential(item)}><span className="grid size-8 place-items-center rounded-md bg-muted"><LockKeyhole className="size-4"/></span><span className="grid"><strong className="text-sm font-medium">{item.name}</strong><small className="text-xs text-muted-foreground">{item.username || 'Kein Benutzername'} · {item.hasPassword ? 'Passwort gesetzt' : 'Kein Passwort'}</small></span></button>)}{!credentials.length && <p className="py-4 text-sm text-muted-foreground">Noch keine Profile vorhanden.</p>}</div></div><form className="grid content-start gap-4 p-5" onSubmit={submitForm(saveCredential)}><h3 className="text-sm font-semibold">{editCredential ? 'Profil bearbeiten' : 'Neues Profil'}</h3><Field label="Bezeichnung"><Input name="name" defaultValue={editCredential?.name ?? ''} placeholder="z. B. Firewall Admin" required key={`n-${editCredential?.id}`}/></Field><Field label="Benutzername"><Input name="username" defaultValue={editCredential?.username ?? ''} autoComplete="off" key={`u-${editCredential?.id}`}/></Field><Field label="Passwort" hint={editCredential ? 'Leer lassen, um das bestehende Passwort beizubehalten.' : undefined}><Input name="password" type="password" autoComplete="new-password" key={`p-${editCredential?.id}`}/></Field><div className="flex flex-wrap justify-end gap-2">{editCredential && <Button type="button" variant="danger" icon={<Trash2/>} onClick={async () => { if (!confirm('Zugangsdatenprofil wirklich löschen?')) return; await remove(`/api/credentials/${editCredential.id}`); setEditCredential(null); await reload() }}>Löschen</Button>}<Button type="button" variant="ghost" onClick={() => setEditCredential(null)}>Leeren</Button><Button type="submit">Speichern</Button></div></form></div></Modal>}
  </>
}
